[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios"]

[build.environment]
  NODE_VERSION = "18"

# Правило для tonconnect-manifest.json
[[redirects]]
  from = "/tonconnect-manifest.json"
  to = "/tonconnect-manifest.json"
  status = 200

# Правило для других статических файлов (например, assets)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Редирект для SPA (все остальные маршруты)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
