[build]
  publish = "dist"          # Папка сборки Vite
  command = "npm run build" # Команда сборки
  functions = "netlify/functions" # Папка с функциями

[dev]
  command = "vite"          # Для локальной разработки

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios"]

[build.environment]
  NODE_VERSION = "18"