import { createApp } from "vue";
import { createPinia } from "pinia";
import "./style.css";
import App from "./App.vue";
import router from "./router";
import { WebApp } from "@twa-dev/sdk";
WebApp();
const tg = window.Telegram?.WebApp;
tg.ready();
tg.expand();
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.mount("#app");
